services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - unuko-net

  open5gs-hss:
    image: openverso/open5gs-webui:2.7.0
    container_name: open5gs-hss
    depends_on:
      - mongo
    command: open5gs-hssd
    ports:
      - "9998:9999" # Lo mapeamos al 9998 para no chocar con el SMF
    volumes:
      - ./config/hss.yaml:/opt/open5gs/etc/open5gs/hss.yaml:ro
    networks:
      - unuko-net

  open5gs-smf:
    image: openverso/open5gs-webui:2.7.0
    container_name: open5gs-smf
    depends_on:
      - mongo
    command: open5gs-smfd
    ports:
      - "9999:9999" # Mapeamos el puerto para que el curl funcione
    networks:
      - unuko-net

  ueransim:
    image: free5gc/ueransim:latest
    container_name: ueransim
    privileged: true
    tty: true
    # Iniciamos un mock listener en 37412 para que el orquestador pueda conectar
    # y usamos tail para mantener el contenedor vivo.
    # Usamos python3 para mockear el listener ya que nc no está instalado en la imagen
    command: sh -c "echo 'Mocking UERANSIM APDU interface on 37412...' && python3 -c 'import socket; s=socket.socket(); s.bind((\"0.0.0.0\", 37412)); s.listen(5); print(\"Listening...\"); [s.accept() for _ in iter(int, 1)]' & tail -f /dev/null"
    networks:
      - unuko-net
    ports:
      - "37412:37412"

  smdp-mock:
    build:
      context: .
      dockerfile: apps/smdp-mock/Dockerfile
    container_name: smdp-mock
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - unuko-net

networks:
  unuko-net:
    driver: bridge

volumes:
  mongodb_data:
