import { SgpResponseHeader } from './types';

export const MOCK_HEADERS: { SUCCESS: SgpResponseHeader } = {
  SUCCESS: {
    functionExecutionStatus: { status: "Executed-Success" }
  }
};

export const MOCK_DATA = {
  TRANSACTION_ID: "tx-2026-smdp-mock-v2",
  CI_PK_ID: "A1B2C3D4E5F67890",
  SERVER_CERTIFICATE: "MIIB7zCCAXagAwIBAgIQ...REAL_MOCK_SMDP_CERT_BASE64...",
  SERVER_SIGNED_1_BASE64: "Ym9yZGVyY29sbGllLXdhbHQtMjAyNi1zbWRwLW1vY2stdjI=",
  SERVER_SIGNATURE_1: "MEUCIQDF3iK4m9Z3xP3zL9QkMOCK_SIGNATURE_DER_BASE64...",
  PROFILE_METADATA: "BF2681A3...MOCK_PROFILE_METADATA_ASN1_BASE64...",
  BOUND_PROFILE_PACKAGE: "BF3681ED...MOCK_BOUND_PROFILE_PACKAGE_ASN1_BASE64...",
  SMDP_SIGNATURE_2: "MEUCIQDh4j...MOCK_SIGNATURE_2_DER_BASE64..."
};