import { Request, Response } from 'express';
import { z } from 'zod';
import { MOCK_SGP32_HEADERS, MOCK_SGP32_DATA } from '../../constants';

const base64Regex = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/;

export const IotAuthenticateClientRequestSchema = z.object({
  transactionId: z.string().min(1, "El transactionId es obligatorio"),
  // Authentication binary ASN.1 sequence generated by the IoT eUICC in Base64
  authenticateServerResponse: z.string().regex(base64Regex, "El bloque authenticateServerResponse debe ser un Base64 válido"),
});

export type IotAuthenticateClientRequest = z.infer<typeof IotAuthenticateClientRequestSchema>;

export const authenticateClientIot = (req: Request, res: Response) => {
  const result = IotAuthenticateClientRequestSchema.safeParse(req.body);

  if (!result.success) {
    return res.status(400).json({
      error: "Invalid Request Payload - Error en validación criptográfica SGP.32",
      details: result.error.format()
    });
  }

  const { transactionId } = result.data;

  console.log(`[SM-DP+ IoT] -> [ESipa.authenticateClient]`);
  console.log(`              Transaction ID: ${transactionId}`);
  console.log(`              Validando firma criptográfica M2M de la eUICC... OK`);

  return res.json({
    header: MOCK_SGP32_HEADERS.SUCCESS,
    transactionId: transactionId,
    profileMetadata: "BF2681A3...MOCK_IOT_PROFILE_METADATA_BASE64...",
    smdpSigned2: {
      transactionId: transactionId,
      ccRequiredFlag: false,
      bppEuiccSignCert: "MIIB7zCCAXagAwIBAgIQ...MOCK_IOT_BPP_EUICC_SIGN_CERT...",
      bppEumSignCert: "MIIB7zCCAXagAwIBAgIQ...MOCK_IOT_BPP_EUM_SIGN_CERT..."
    },
    smdpSignature2: MOCK_SGP32_DATA.SERVER_SIGNATURE_1,
    smdpCertificate: MOCK_SGP32_DATA.SERVER_CERTIFICATE
  });
};