import { Request, Response } from 'express';
import { z } from 'zod';
import { MOCK_SGP32_HEADERS, MOCK_SGP32_DATA } from '../../constants';

const base64Regex = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/;

export const IotGetBoundProfilePackageRequestSchema = z.object({
  transactionId: z.string().min(1, "El transactionId es obligatorio"),
  //ASN.1 binary sequence of download confirmation generated by the IoT eUICC in Base64
  prepareDownloadResponse: z.string().regex(base64Regex, "El bloque prepareDownloadResponse debe ser un Base64 válido"),
});

export type IotGetBoundProfilePackageRequest = z.infer<typeof IotGetBoundProfilePackageRequestSchema>;

export const getBoundProfilePackageIot = (req: Request, res: Response) => {
  const result = IotGetBoundProfilePackageRequestSchema.safeParse(req.body);

  if (!result.success) {
    return res.status(400).json({
      error: "Invalid Request Payload - Error en empaquetado BPP de IoT",
      details: result.error.format()
    });
  }

  const { transactionId } = result.data;

  console.log(`[SM-DP+ IoT] -> [ESipa.getBoundProfilePackage]`);
  console.log(`              Transaction ID: ${transactionId}`);
  console.log(`              Generando chorro binario cifrado BPP para entorno IoT...`);

  return res.json({
    header: MOCK_SGP32_HEADERS.SUCCESS,
    transactionId: transactionId,
    boundProfilePackage: MOCK_SGP32_DATA.BOUND_PROFILE_PACKAGE_IOT
  });
};